language: php

php:
- '7.3'
env:
  global:
  - ZIP_FILENAME=bmlt-meeting-map-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=bmlt-meeting-map
jobs:
  include:

  - stage: lint
    install:
    - composer install
    script:
    - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
    - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=bmlt-meeting-map.zip
    - PLUGIN="bmlt-meeting-map"
    - MAINFILE="meeting_map.php"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*" -x "*assets*" -x "*vendor*" -x "composer.*" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    - curl -LO https://raw.githubusercontent.com/bmlt-enabled/bmlt-wordpress-deploy/master/deploy-wordpress.sh
    - chmod +x deploy-wordpress.sh
    deploy:
    - provider: s3
      access_key_id: AKIA3EWZC3OHKYCL5SIY
      secret_access_key:
        secure: cE3Cvp/spOGGH9qnFAZ79D2QqSHVHqS1h/UcjGs3xjpIfet3wGb/seWOCTh3f3tplyTFW6MLEQ1ZuLLdgC6lhB5X0KaLS6/yJfowsZQP9gB7aGRK3t+ji0QJPrXxj8ZKgBCyPfcBxyPMxvXpxNkbLAGcLXvWBOytJI40qekiNU1RnJrK3CJE8zB4KjMYuN4yqIEL0uU7pEGOj6wcycXjkqRI+c6hEGKpFqrf83Sg3KIvY45JaNrho04GWdscauyhmsXdccmIKmeYhQREHgnd8m6R7pfhHYZwCI0M6D3PNOC6LkVESeCzd32x0rPmzODbJlrAp3n0gpxsjT5XEw1YmaCXq3rLwFTFVlEjh1RIgE09VQ3w9cDX43Xoc032YdOv1/SsvctlS6Q+a8u44B+oWIBJal30lu0F5rmli9/iXMalB+bsPo3CbZEFeoTRWDfzIHpXKMWKz1IcNzt824oLSNp+2eZc+oZJLejF3BzkGCJVS50wPXPqkdljKt0oT07lYj6P8GfR3HKwvIL7Z32IlV3cCfQvjzDi0YDr//CXdQ3qdeOlgUsHcmmxx4k58LxJtnsZfkJ9KyHnq341S6MjiUNrlMTcxTVED8KokfLd3dgEPSR5vBosyO0ZyWjMgo473vdZpJzJnqsQC3MEqC/Tfht+n2M2gpfJ9aaeCod9k+M=
      bucket: "$S3_BUCKET"
      local_dir: "$DIST_DIR_S3"
      upload-dir: "$S3_KEY"
      skip_cleanup: true
      on:
        all_branches: true
    - provider: releases
      api_key:
        secure: v9E2gEJswaoxJ/6q0RZMTXmyGh8+KB9fQIHo6Wl3VATjTW6lVBh7QK6Xwz9ghyICfnkKjLvquoOROwCUqMmo/fub9tmGXnkVtREj4g6Pp/dE5Og9bJGKHHnGH00dKtM84yTot4M6Y0iDM6ci2hbvWkI3UACUD0+y01SxAvS/9ZIKS52ApvdQnrwYT+2/NP0yaSehpahzez4tWWA30wQMFBJsfZPa91IAQCTi+XcKHHq7k6zbBzVHOqADmUAfkwd0JqB0eNZ9SLDZT/4Dp/BJa7DpinxhqozFO790eqsQT+J1eXX4DgiarLLmGEpaGPa6zwqKlPhsv0WIZLPbunEa+nvxljCgfk3wE9fEMc/OYvKZIH3Ulm3T/Cdrx0JLVtAO3f2X/9rPXxT0re0rjdHVUkYk5qs+IQK77t2wqfF9L9eoAalP8HxAzuc0fzl8JJaa3angbkXtJ4wkUC2DeEyniHrZKkKT6OZFu2JyZ0cgrXsDqVqmdCfNSvbs0SOUMU8E1hl/xK8nH3Jsj46AyiNo7gNwjy8AP69q0xyvq1eFX2PC6AREmlriJVQsdf6ZKRkiNwzFGgUzwThq6kx68fMEOraGfWE+uVhA10mKJBEQa2yGugAN7emkvjXYHYh4bZ8qce+gMpq6EiZor7ZarBRAqjElA9wBS5zewNb+aaF9OjE=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      on:
        tags: true
    - provider: script
      script: ./deploy-wordpress.sh
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    rooms:
    - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false
